// Pre-loaded realistic university course modules for instant exploration
window.SAMPLE_MODULES = [
  {
    id: "cs301",
    code: "CS301",
    title: "Distributed Systems & Consensus Protocols",
    department: "Computer Science & Engineering",
    pages: 14,
    words: 4250,
    academicLevel: "Undergraduate / Year 3",
    description: "Covers fault tolerance, CAP theorem, Paxos, Raft consensus, vector clocks, and Byzantine fault tolerance in distributed computing.",
    sections: [
      { id: "s1", page: 1, title: "1. Introduction to Distributed Systems & Fault Models", text: "A distributed system consists of autonomous computing entities that communicate over a network to achieve a common goal. Unlike centralized systems, distributed systems face partial failures, network partitions, and asynchronous message delivery. Fault models range from crash-stop (nodes fail and stay down), crash-recovery (nodes can reboot after failure), to Byzantine faults (nodes may behave arbitrarily, send conflicting data, or act maliciously). Lamport's famous quote summarizes the dilemma: 'A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.'" },
      { id: "s2", page: 3, title: "2. The CAP Theorem & Consistency Models", text: "Formulated by Eric Brewer and proven by Gilbert & Lynch, the CAP theorem states that any distributed data store can simultaneously provide at most two out of three guarantees: Consistency (every read receives the most recent write or an error), Availability (every non-failing node returns a response, without guarantee that it is the most recent write), and Partition Tolerance (the system continues to operate despite arbitrary message loss or delay). Because network partitions (P) are inevitable in real-world networks, distributed systems must trade off between C and A. Strong consistency models include Linearizability and Sequential Consistency, whereas weaker models include Eventual Consistency, Causal Consistency, and Read-Your-Writes consistency." },
      { id: "s3", page: 6, title: "3. Logical Time & Vector Clocks", text: "Physical clocks in computer hardware drift due to crystal oscillator variance and temperature shifts (clock skew). Network Time Protocol (NTP) provides synchronization within milliseconds, but cannot establish strict causal ordering. Leslie Lamport introduced Logical Clocks (Lamport Timestamps) based on the 'happened-before' relation (→). If event a happened before b, then L(a) < L(b). However, L(a) < L(b) does not imply a → b (they could be concurrent). Vector Clocks solve this limitation by maintaining an array of logical clocks across all N processes: V[i] tracks process i's local time, and vector comparisons allow exact determination of whether two events are causally related or concurrent (a || b)." },
      { id: "s4", page: 9, title: "4. Raft Consensus Algorithm", text: "Consensus is the fundamental problem of agreeing on a single data value or log entry among multiple nodes. While Paxos was historically dominant, its formulation is notoriously difficult to understand and implement. Ongaro and Ousterhout developed Raft as an understandable alternative based on decomposed state machine replication. Raft divides consensus into three subproblems: Leader Election, Log Replication, and Safety. Raft nodes exist in one of three states: Follower, Candidate, or Leader. Time is divided into terms of arbitrary length, represented by consecutive integers. A leader is elected via majority votes (quorums: > N/2). The leader accepts log proposals from clients, replicates them across followers, and commits entries once acknowledged by a majority." },
      { id: "s5", page: 12, title: "5. Byzantine Fault Tolerance (BFT)", text: "Crash-fault tolerant protocols (Raft, Paxos) assume nodes are non-malicious and follow the protocol truthfully. In adversarial environments or decentralized networks (e.g., blockchain), nodes can act arbitrarily. Castro and Liskov introduced Practical Byzantine Fault Tolerance (PBFT) in 1999. In a system with f Byzantine nodes, PBFT requires a minimum of 3f + 1 total nodes to guarantee safety and liveness (a 2/3 supermajority). The protocol executes in three phases: Pre-Prepare (primary assigns sequence number), Prepare (nodes broadcast prepare messages to establish ordering), and Commit (nodes broadcast commit messages to confirm quorum consensus)." }
    ]
  },
  {
    id: "bio204",
    code: "BIO204",
    title: "Cellular Respiration & Metabolic Bioenergetics",
    department: "Biological Sciences",
    pages: 12,
    words: 3820,
    academicLevel: "Undergraduate / Year 2",
    description: "Detailed analysis of Glycolysis, the Pyruvate Dehydrogenase complex, Krebs Cycle, Electron Transport Chain, and Chemiosmosis.",
    sections: [
      { id: "s1", page: 1, title: "1. Overview of Cellular Energy Harvest", text: "Cellular respiration is the catabolic pathway by which organic molecules are oxidized to generate adenosine triphosphate (ATP), the universal chemical energy currency of biological organisms. The overall stoichiometric equation for aerobic respiration of glucose is: C6H12O6 + 6 O2 → 6 CO2 + 6 H2O + ~30-32 ATP. The process spans four major stages: Glycolysis (cytosol), Pyruvate Oxidation (mitochondrial matrix), the Citric Acid / Krebs Cycle (mitochondrial matrix), and Oxidative Phosphorylation (inner mitochondrial membrane cristae)." },
      { id: "s2", page: 3, title: "2. Glycolysis: Splitting Glucose", text: "Glycolysis occurs in the cytosol without requiring oxygen. A 10-step enzymatic cascade splits 1 molecule of 6-carbon glucose into 2 molecules of 3-carbon pyruvate. It consists of two phases: the Energy Investment Phase (consumes 2 ATP via hexokinase and phosphofructokinase-1) and the Energy Payoff Phase (produces 4 ATP via substrate-level phosphorylation and 2 NADH). Net yield per glucose: 2 ATP, 2 NADH, and 2 Pyruvate. Phosphofructokinase-1 (PFK-1) is the principal allosteric rate-limiting enzyme, inhibited by high ATP and citrate, and activated by AMP and fructose-2,6-bisphosphate." },
      { id: "s3", page: 6, title: "3. Pyruvate Oxidation & The Krebs Cycle", text: "Pyruvate is transported across the mitochondrial membranes via the mitochondrial pyruvate carrier (MPC). In the matrix, the multi-enzyme Pyruvate Dehydrogenase Complex (PDC) catalyzes oxidative decarboxylation: Pyruvate + CoA + NAD+ → Acetyl-CoA + CO2 + NADH. Acetyl-CoA enters the Citric Acid Cycle, condensing with 4-carbon oxaloacetate to form 6-carbon citrate via citrate synthase. Over 8 enzymatic steps, 2 carbons are released as CO2, generating 3 NADH, 1 FADH2, and 1 GTP (or ATP) per turn. Since 1 glucose yields 2 pyruvates, the cycle turns twice per glucose, producing 6 NADH, 2 FADH2, 2 ATP/GTP, and 4 CO2." },
      { id: "s4", page: 9, title: "4. The Electron Transport Chain & Chemiosmosis", text: "High-energy electron carriers (NADH and FADH2) transfer electrons through four multi-protein complexes embedded in the inner mitochondrial membrane: Complex I (NADH-Q oxidoreductase), Complex II (succinate-Q reductase), Complex III (Q-cytochrome c oxidoreductase), and Complex IV (cytochrome c oxidase). Mobile carriers ubiquinone (coenzyme Q) and cytochrome c shuttle electrons. Electron transfer is exergonic and drives proton (H+) pumping from the matrix into the intermembrane space at Complexes I, III, and IV, establishing an electrochemical proton gradient (proton motive force: Δp = ΔΨ + ΔpH). Peter Mitchell's chemiosmotic hypothesis explains how protons flow down their gradient back into the matrix through ATP Synthase (F0F1 complex), driving rotational catalysis to phosphorylate ADP into ATP." },
      { id: "s5", page: 11, title: "5. Anaerobic Pathways & Fermentation", text: "In the absence of molecular oxygen, the electron transport chain halts because oxygen is the terminal electron acceptor. NADH accumulates, depriving glycolysis of NAD+ needed at step 6 (GAPDH). Fermentation solves this by regenerating NAD+ without oxidative phosphorylation. In lactic acid fermentation (human muscle cells, lactobacilli), lactate dehydrogenase reduces pyruvate to lactate while oxidizing NADH to NAD+. In alcoholic fermentation (yeast), pyruvate decarboxylase converts pyruvate to acetaldehyde, which is reduced to ethanol by alcohol dehydrogenase, regenerating NAD+." }
    ]
  },
  {
    id: "fin402",
    code: "FIN402",
    title: "Modern Portfolio Theory & Asset Pricing Models",
    department: "Finance & Quantitative Economics",
    pages: 16,
    words: 4600,
    academicLevel: "Graduate / Year 4",
    description: "Markowitz mean-variance optimization, the Efficient Frontier, Capital Asset Pricing Model (CAPM), Beta estimation, and Arbitrage Pricing Theory.",
    sections: [
      { id: "s1", page: 1, title: "1. Foundations of Risk and Return", text: "Modern portfolio analysis begins with Harry Markowitz's seminal 1952 paper demonstrating that an asset's risk should not be assessed in isolation, but by its contribution to an overall portfolio's risk and return. The expected return of an asset is its probability-weighted payoff, while risk is quantified as the variance or standard deviation of returns (volatility, σ). Markowitz showed that diversification reduces unsystematic (idiosyncratic) risk when asset returns are imperfectly correlated (correlation coefficient ρ < 1). However, systematic (market-wide) risk cannot be eliminated through diversification." },
      { id: "s2", page: 4, title: "2. Mean-Variance Optimization & The Efficient Frontier", text: "For an N-asset universe, an investor seeks portfolio weights w_i that minimize variance for a given target expected return, subject to Σ w_i = 1. Plotting all possible portfolios in expected return (E[R]) vs. standard deviation (σ) space yields the investment opportunity set. The upper boundary is the Efficient Frontier: the set of optimal portfolios that offer the highest expected return for a defined level of risk, or the lowest risk for a given expected return. Portfolios below the frontier are sub-optimal because higher returns are achievable at equivalent risk levels." },
      { id: "s3", page: 7, title: "3. The Capital Market Line & The Tangency Portfolio", text: "James Tobin introduced the concept of a risk-free asset (yielding return R_f with σ = 0, such as short-term sovereign treasury bills). Combining the risk-free asset with a risky portfolio creates the Capital Allocation Line (CAL). The steepest possible CAL is tangent to the Markowitz Efficient Frontier at exactly one portfolio: the Tangency Portfolio (or Market Portfolio M in equilibrium). This optimal line is the Capital Market Line (CML): E[R_p] = R_f + ((E[R_m] - R_f) / σ_m) * σ_p. The slope of the line is the Sharpe Ratio, representing excess return per unit of total risk." },
      { id: "s4", page: 10, title: "4. The Capital Asset Pricing Model (CAPM) & Beta", text: "Developed independently by Sharpe, Lintner, and Mossin, the CAPM extends portfolio theory to individual asset valuation in equilibrium. CAPM asserts that investors are compensated only for systematic risk, measured by Beta (β): β_i = Cov(R_i, R_m) / Var(R_m). Beta reflects an asset's sensitivity to market movements: β > 1 indicates aggressive/volatile assets, β = 1 mirrors the market, and β < 1 indicates defensive assets. The Security Market Line (SML) specifies the expected return: E[R_i] = R_f + β_i * (E[R_m] - R_f), where (E[R_m] - R_f) is the Market Risk Premium (MRP). Jensen's Alpha (α) measures performance above or below the SML." },
      { id: "s5", page: 14, title: "5. Multifactor Models & Arbitrage Pricing Theory (APT)", text: "Recognizing that CAPM assumes a single market risk factor, Stephen Ross developed Arbitrage Pricing Theory (APT), which posits that expected returns depend on multiple macroeconomic and fundamental risk factors (e.g., unexpected inflation, industrial production, interest rate yield spread, GDP growth). Eugene Fama and Kenneth French introduced empirical multi-factor models: the Fama-French Three-Factor Model augments market return with SMB (Small Minus Big, capturing the size premium) and HML (High Minus Low, capturing the value premium based on book-to-market ratio), later expanded to five factors including profitability (RMW) and investment aggressiveness (CMA)." }
    ]
  }
];
